# Generated by Django 5.2 on 2025-04-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresslog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], max_length=20),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='task_title',
            field=models.CharField(max_length=255),
        ),
    ]
