# Generated by Django 5.2 on 2025-04-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_progresslog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresslog',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa hoàn thành'), ('done', 'Đã hoàn thành')], default='pending', max_length=20),
        ),
    ]
